[[redirects]]
from = "/signin" # Replace with your route path
to = "/index.html"
status = 200

[[redirects]]
from = "/home"   # Replace with your route path
to = "/index.html"
status = 200

[[redirects]]
from = "/tasks"  # Replace with your route path
to = "/index.html"
status = 200

# Add more redirect rules for other routes as needed
[[redirects]]
from = "/notfound"   # Replace with your 404 page path
to = "/path/to/404/page"  # Replace with the actual path to your custom 404 page
status = 404
